services:
  versa:
    build: .
    image: versa:latest
    container_name: versa
    environment:
      - VERSA_BASE_URL_PATH=/salesbuilder
      - VERSA_DATA_ROOT=/.versa
    volumes:
      - /usr/share/nginx/html/:/downloads
      - config:/.versa
    network_mode: host
    restart: on-failure

volumes:
  config:
